web/model-manager.js
Added an argument to the `refreshModels` function, which determines whether comfy refresh will be called. The rest of the logic and model grid update is still executed.
When Comfy won't refresh:
- Initial page load
- Preview update
- Saving settings
- Reload settings
- Fix Extensions button
=> Removing unnecessary comfy refresh calls

__init__.py, web/model-manager.css, web/model-manager.js
Added preview size sliders to settings
Added 'Show buttons on hover only' checkbox for preview buttons
=> Preview size sliders 

py/utils.py
=> fix: Cross-device movement

__init__.py, py/download.py, py/services.py, py/utils.py, src/components/DialogModelDetail.vue, src/components/ModelBaseInfo.vue, src/components/ModelCard.vue, src/components/ModelDescription.vue, src/components/ResponseInput.vue, src/hooks/model.ts, src/i18n.ts, src/style.css, vite.config.ts
- Fix the bug of incorrect saving description in windows
- Fix the bug of inconsistent paths on windows
- Add directory display in the model information
- Fix other known issues
- Optimize some styles
=> Update: resolving windows issue and enhancing model display

src/components/DialogCreateTask.vue, src/components/DialogManager.vue, src/components/ResponseScroll.vue
* keep model preview status after toggle model tag in create download task
* keep model list scrollbar position after saving model
=> Feature optimize UI

README.md
Resolve #52 , update installation description.
=> chore: update installation explanation

py/services.py, py/utils.py, pyproject.toml
Fix #55 
- Add scanning of `.preview.ext` files.
- Removed ability to delete old files.
=> Fix missing preview 

__init__.py, py/services.py
- Fix the problem of incorrect error message
- Format remove blank lines
=> Fix some minor bug

py/services.py
=> Fix preview path

__init__.py, py/services.py, src/App.vue, src/components/DialogManager.vue, src/components/ModelBaseInfo.vue, src/hooks/config.ts, src/hooks/model.ts
Get the model list separately by model type and defer the request.
=> Split model get list API

package.json, pnpm-lock.yaml, src/components/DialogDownload.vue, src/components/DialogManager.vue, src/components/ModelCard.vue, src/components/ModelContent.vue, src/components/ModelPreview.vue, src/hooks/container.ts, src/main.ts, src/types/shims.d.ts, tailwind.config.js
Fixed #57 
Fixed #81 
- Use js dynamic calculation instead of container queries
- Remove @tailwindcss/container-queries
=> fix: Container queries occasionally fail

src/hooks/config.ts, src/i18n.ts, src/types/global.d.ts
- fix getting language configuration
- add setting's i18n
=> Fix: i18n settings

__init__.py, py/config.py, py/utils.py, src/hooks/config.ts, src/hooks/model.ts, src/i18n.ts
Resovled #86 , specified directories can be added to exclude model scans.
=> feat: add exclude scan model types

src/hooks/dialog.ts
- Add optional parameters to the close function to support parameterless calling
- When the dialog parameter is not provided, automatically close the dialog box on the top of the stack
=> feat(dialog): Optimize dialog closing logic

__init__.py, py/download.py, py/services.py, py/utils.py, src/components/DialogCreateTask.vue, src/components/DialogModelDetail.vue, src/components/ModelContent.vue, src/hooks/model.ts, src/types/typings.d.ts, src/utils/common.ts
=> fix: can't change or delete preview

src/components/ResponseSelect.vue
=> fix: Inability to Scroll model dir list

__init__.py, py/utils.py
=> feat: add deprecated decorator

src/components/GlobalDialogStack.vue
Use primevue config zIndex to be base-z-index.
=> fix: set base-z-index

src/components/DialogDownload.vue, src/components/DialogManager.vue, src/components/ModelContent.vue, src/components/ResponseScroll.vue, src/components/ResponseSelect.vue, src/hooks/container.ts, src/hooks/resize.ts, src/hooks/scroll.ts, src/main.ts, src/types/shims.d.ts
- remove v-resize
- add useContainerResize
- remove v-container
- add useContainerQueries
- add useContainerScroll
=> pref: use hooks instead of directive

package.json, pnpm-lock.yaml, src/components/ResponseScroll.vue
Add dependencies @vueuse/core.
Drag the scroller thumb can scroll the content.
=> feat: add scroll thumb draggable

src/components/DialogManager.vue, src/components/SettingCardSize.vue, src/hooks/config.ts, src/i18n.ts
Resovle #123 .
Remove card size setting. Replace with allow user customization common sizes.
=> feat: optimize resize card size

py/manager.py, src/App.vue, src/components/DialogExplorer.vue, src/components/DialogManager.vue, src/components/DialogModelDetail.vue, src/components/ModelBaseInfo.vue, src/components/ModelCard.vue, src/components/ResponseBreadcrumb.vue, src/components/ResponseDialog.vue, src/components/ResponseInput.vue, src/components/ResponseScroll.vue, src/components/ResponseSelect.vue, src/hooks/config.ts, src/hooks/dialog.ts, src/hooks/explorer.ts, src/hooks/model.ts, src/i18n.ts, src/types/typings.d.ts, src/utils/model.ts, tailwind.config.js
A new UI.
Display a list of models using a tree structure.
Resolve #85
=> [New Feature] sub directories support

src/components/DialogExplorer.vue, src/components/DialogManager.vue
=> feat: support search sub folder

py/manager.py, src/components/DialogExplorer.vue, src/components/DialogManager.vue, src/components/ModelCard.vue, src/hooks/explorer.ts, src/hooks/model.ts, src/types/typings.d.ts
Fixed folders in search results not to be opened correctly.
=> refactor(explorer): optimize openFolder

py/information.py, py/manager.py, py/utils.py, src/components/ModelCard.vue, src/components/ModelPreview.vue, src/hooks/model.ts, src/types/typings.d.ts
Resolve #124 
Support gif, video.
=> Feat optimize preview

__init__.py
Experimental feature:
The model supports the gguf extension.
=> [Experimental] Support extension gguf

.github/workflows/publish.yml, pyproject.toml
=> 178 bug borderline race condition

py/download.py, py/information.py, py/manager.py, py/utils.py, src/components/DialogDownload.vue, src/components/ModelCard.vue, src/components/ModelPreview.vue, src/components/PreviewVideo.vue, src/components/ResponseFileUpload.vue, src/hooks/explorer.ts, src/hooks/model.ts, src/types/typings.d.ts, src/utils/media.ts
This was my first test run trying out Claude Code. It went a little wild and I spent a bit of time manually reining it back in to minimize what was changed. Overall I'm considering it a success since it mostly worked and I had no prior experience working in a ComfyUI extension or a Vue based UI. So it PROBABLY was faster than me figuring it all out from scratch, but who knows.
If there's anything else you'd like me to clean up or do differently, let me know.
=> add support for video previews

py/manager.py, py/utils.py, pyproject.toml
I was struggling every time I refetch my folders due I have stored my models in a HDD, and are around of 8000+. It was due it was reading the whole folder for every file in my storage searching for the preview. It was taking around of 15 minutes every refresh or restart ( the main problem was the use of search_files and folder_paths.filter_files_content_types). Additionally I set a batch size for reading for prevent saturation in the I/O.
Now it loads the files blazing fast in comparison (less than 5 seconds) without needing a cache or something like that.
=> Improvements in previews reading
